# Generated by Django 4.2.30 on 2026-07-07 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='QUEUED', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('input_file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('target_columns', models.JSONField(default=list)),
                ('nl_prompt', models.TextField()),
                ('replacement_value', models.CharField(max_length=500)),
                ('regex_pattern', models.TextField(blank=True, default='')),
                ('result_file', models.FileField(blank=True, null=True, upload_to='results/')),
                ('total_rows', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
